### ISSUE TITLE
Premium mängija ei saa vote auhinda, kui ta pole mängus.

### ISSUE THREAD

**Issue by mikroskeem** [mikroskeemsrealm/msb-tracker#1]
Praegune vote auhinna [plugin](https://www.spigotmc.org/resources/superbvote.11626/) ei tööta _hybrid_ tüüpi serveris korrektselt.

Nimelt preemium kontodele ei tule auhindu kui antud mängijad on votenud ilma, et nad mängus oleksid; see on sellepärast, et plugin kasutab UUID-sid _queue_ jaoks ning need ei ühti preemium kontode omadega.

Võimalikud lahendused:
- Viia sisse muudatused pluginasse, et kasutaks kasutajanimesid _queues_
- Luua enda vote auhinna plugin.

**Comment by DirolGaming** [comment]
Arvan, et omaenda vote plugina loomine on veidike aja raiskamine, aga kui ajaga paremat midagi teha pole, siis anna tuld. 🗡

**Comment by mikroskeem** [comment]
Lihtne task ju :^)

**Comment by DirolGaming** [comment]
Kõlab, nagu plaan valmis, milleks siis lisada erinevad variandid, kui endal juba kindel ja "lihtne" plaan olemas?

**Comment by mikroskeem** [comment]
Erinevad valikud on ikka mõistlik kirja panna, in case kui on vaja meelt muuta. Siis ei pea pärast meenutama teisi võimalusi.

Siin on küll 2 varianti aga samasuguse reegli järgimine tuleb vägagi kasuks kohtades, kus neid rohkem on.
