### ISSUE TITLE
Koduleht

### ISSUE THREAD

**Issue by mikroskeem** [mikroskeemsrealm/msb-tracker#2]
Serverile oleks vaja seadistada koduleht, kus oleks üleval serveri informatsioon ja muu vajalik kraam.

**Comment by mikroskeem** [comment]
Ehk siis on vaja sellele edasiarendust teha: https://github.com/kaevupoiss/WebSite

**Comment by mikroskeem** [comment]
Demo asub siin: https://warp.cybergaming.ee/

**Comment by DirolGaming** [comment]
Arvan, et disaini võiks kindlasti parandada. Näiteks ülemine must riba võiks olla olematu ja "Home" tekst kas siis üldse eemaldatud(kuna menüüs olevad asjad on suhteliselt selged ja siiski koduleht on lihtsa süsteemiga, siis pole suurt vajadust inimesel teada, kas ta "Home" või kuskil mujal), või siis sama stiiliga tehtud, kui standard tekst "Mikroskeem's SkyBlock". Arvan, et terve kodulehe mulje oleks parem, kui menüüde jne taust oleks kas transparent või hästi õrnalt tumedam kui ülejäänu. Leian ka seda, et tavakasutaja jaoks oleks mugav, kui kodulehel oleks siis veidike täpsem info serveri kohta ja selle eelised. Nt kerid alla "home" lehel ning siis allpool on erinevad eelised või omapärasused, mis serveril on jne.
